FROM python:3.8

RUN pip3 install --upgrade pip \
    && pip3 install detoxify flask
COPY src ./src
RUN chmod -R 777 ./src
RUN python ./src/download_model.py
EXPOSE 5000
CMD python ./src/run_service.py
